version: "3.2"
services:
  worker:
    image: chiwanpark/crawler:latest
    networks:
      - backend
    logging:
      driver: journald
    environment:
      WORKER: "{{ .Node.Hostname }}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SLEEP_QUEUE_EMPTY: 60
    deploy:
      mode: global
      resources:
        reservations:
          cpus: "1"
          memory: 256M 
      placement:
        constraints:
          - node.labels.crawler == on

networks:
  backend:
    external: true
